### ISSUE TITLE
Version 1.3.0 of BalancedItems breaks suit rack when enabled with LethalExpansion

### ISSUE THREAD

**Issue by ssbanerjee** [Doug-Murphy/LethalCompanyMods#16]
Obviously not a huge issue, and my apologies if this issue is not something worth looking into due to how specific it is.

As odd as it sounds, the new version of **BalancedItems** inexplicably breaks the suit rack, causing none to appear, but only when enabled alongside **LethalExpansion** by **HolographicWings**. To be more specific, the suit rack itself is there, but no suits load. This is preventing the ability to change suits (which naturally also affects any mods that add suits to the rack).

I did about an hour of testing different versions with every combination of mods I have to reproduce the error, and the only state where the suit rack breaks is when **LethalExpansion** is enabled with **version 1.3.0** of **BalancedItems**. Having either single mod enabled on its own is fine, but the suit rack breaks when they're both on.

I originally thought the issue was **LethalExpansion**, but based off my testing it seems like it could be **BalancedItems**.
Reverting back to **version 1.2.0** of **BalancedItems** does _not_ break the suit rack, so it's specifically an issue with **version 1.3.0**. I confirmed this by switching versions multiple times with **LethalExpansion** both enabled and disabled.
Reverting **LethalExpansion** back to earlier versions does not fix the issue, so I don't think the problem is with that mod and likely is originating with this one. Perhaps **version 1.3.0** is now modifying something that **LethalExpansion** uses, which **version 1.2.0** did not.

I'm not really sure what changing scrap item values has to do with the suit rack, so I can only assume it's something related to systemic changes instead. If there's no real way to get around this, feel free to close the issue. I mainly wanted to make it known in case there was a way to keep both mods on and stay up to date.

**Comment by Doug-Murphy** [comment]
Thanks for the report! You definitely did a pretty thorough analysis and I appreciate that. :D I am also confused why this would be an issue, but I have some time tonight where I can look into this and see what I can find out.

I'm not familiar with LethalExpansion so I'll have to look at its code and see what it does.

Are you using any suit mods? Or do you mean the vanilla suits in the game don't work?

**Comment by Doug-Murphy** [comment]
I very quickly created a profile in r2modman that had Balanced Items 1.3.0, BepInExPack 5.4.2100 (dependency) and Lethal Expansion 1.3.18. There were no other mods in this profile. I started up a new session and bought the pajama suit. The suit showed on the rack, and I was able to change into the suit. I confirmed the suit change was in effect when by pulling the lever on the ship and I saw the pajama suit on my arm.

Can you try those steps and see if you see the same?

**Comment by ssbanerjee** [comment]
> Thanks for the report! You definitely did a pretty thorough analysis and I appreciate that. :D I am also confused why this would be an issue, but I have some time tonight where I can look into this and see what I can find out.
> 
> I'm not familiar with LethalExpansion so I'll have to look at its code and see what it does.
> 
> Are you using any suit mods? Or do you mean the vanilla suits in the game don't work?

Whoops, seems like I forgot to mention that in the post. Yeah, I'm using the More_suits mod by x753.
My bad on not mentioning that since that's a bit important. 
I think I didn't test turning it off since the end goal was to have them on to begin with, and that mod also hadn't updated since a few weeks ago.

I'll try testing just the base mods as you did in your more recent post and then with More_suits loaded after work later today. Since a different mod seemed to work for you on your test, then maybe it's some weird intersection with all three.

Unfortunately I'm responding at like 5am because I make poor life choices and can't sleep, so it'll be a bit before I can make that test, lol.

**Comment by Doug-Murphy** [comment]
I just added in More_Suits 1.4.1 created by x753 to my profile for testing. They work fine for me there. I was able to change into Mario, Luigi, and Kirby without any issues.

**Comment by ssbanerjee** [comment]
Hmm, great. So yeah, if I go back to a state where all the mods were working fine, it only works when Balanced_Items is on 1.2. Going up to 1.3 with LE does still break it on my end. BUT, if I take out everything like how you have, then yeah it works.
So that's great.

Here is what I see when I have the other mods on:
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/2807382/7b97f14c-9d0a-45eb-be87-5c30c7997e60)

I had assumed it had to be the only mod that updated on the day it broke that was the root of the issue, especially with an older version working, but it seems I need to start testing again with the other mods so I can find which one is doing it.

**Comment by Doug-Murphy** [comment]
Okie doke! I found the issue. :) In 1.3.0 I introduced a new feature for overriding the scrap spawn rarities on the moons. I made sure to add these overrides to the config file so that you and others could customize it. When adding entries to the config, BepInEx has a certain list of characters that it deems invalid for config section headers and config entry keys. The Dafis_Mega_Moon_Pack_Emporium (sidenote: holy shit that adds a lot of moons!) adds in some moons with invalid configuration value characters, specifically the `'` apostrophe. When my mod was building the list of all spawnable scrap on all moons, it broke when it came to `Peach's Castle`.

I have a fix ready for this and will ship a 1.3.1 tonight!

P.S. 1.4.0 is right around the corner. I could wait til then, but I don't want to hold this up for 1.4.0.

Thanks again for the report!

**Comment by Doug-Murphy** [comment]
Suits on the rack
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/1383347/540c220d-bcb7-454c-ba15-c3e176d59ab7)

Moons in the terminal
![image](https://github.com/Doug-Murphy/LethalCompanyMods/assets/1383347/af7e2438-cf1c-4c04-9b01-13dc5b47e6b1)

**Comment by Doug-Murphy** [comment]
@ssbanerjee 1.3.1 has been released to Thunderstore. If you are still seeing this issue after upgrading to 1.3.1, comment back here and I'll reopen the issue!
