### ISSUE TITLE
Gear Weight

### ISSUE THREAD

**Issue by Kobi-Blade** [Doug-Murphy/LethalCompanyMods#21]
I figured it out thanks to Mike on Discord.

**Comment by Doug-Murphy** [comment]
Glad you could figure it out!

I'll make a suggestion though. Based on your original comment, it looks like you were just trying to make all gear weigh nothing. Is there a particular reason that my mod isn't what you're after? You could set the weight to be 0 for all of the items that you wanted to. Perhaps maybe you were just making a mod as a passion project?

This mod is worth potentially checking out for you.
https://thunderstore.io/c/lethal-company/p/66Studios/No_Weight_Gain/

**Comment by Doug-Murphy** [comment]
Ah yes I see! Totally makes sense. Sometimes the micro slice is precisely (pun intended) what you need. That's actually why my next mod will be _just one thing_ in the terminal. There are other things I want to do in the terminal, but I don't have any intention on packaging them together. :)

For getting the list of items and various properties about them, I'll refer you to how I did it in my mod. :) I find this to be an absolutely invaluable for debugging/mod creation! Happy modding!
https://github.com/Doug-Murphy/LethalCompanyMods/blob/main/GuysNight.LethalCompanyMod.BalancedItems/Patches/StartOfRoundPatches.cs#L20-L27
