### ISSUE TITLE
Invincible Bridge mod; add Adamance bridge

### ISSUE THREAD

**Issue by MetroidCatcher** [Doug-Murphy/LethalCompanyMods#36]
Hello, would you like add the bridge from Adamance as well?
(Seems this bridge is even less sturdy, than the one from Vow)

**Comment by Doug-Murphy** [comment]
@MetroidCatcher Hey there. I quit playing Lethal Company a few months ago, but decided to install it just to take this on as it seemed pretty simple. I just went to the new moon and I'm unable to get the bridge to break with this mod installed. Are you seeing the bridge break while using Invincible Bridge?

**Comment by MetroidCatcher** [comment]
Oh, seems like I didn't used it earlier, my bad. 😅

**Comment by Doug-Murphy** [comment]
Thanks for confirming! :)
