### ISSUE TITLE
[Bug] Softlock on random seed when scrap added to map with other mods

### ISSUE THREAD

**Issue by MathiusXII** [Doug-Murphy/LethalCompanyMods#38]
I use LethalQuantities, but I also use your mod since it does a few things LQ can't, such as setting the weight/prices of the player ragdolls, clipboard, and sticky note, and setting store item prices.

Your mod doesn't support adding new items to maps that don't have them, such as editing chemical jug values for maps other than Vow.

If I add these items with LQ, BalancedItems softlocks on random seed and prints these errors in the console. This is also with "EnableMoonRarityOverrides" set to false, so this shouldn't happen regardless.

(In this case, it was mad that I added Candy to Assurance)

[16:37:47.7391854] [Error  : Unity Log] KeyNotFoundException: The given key 'Candy' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_001E)
GuysNight.LethalCompanyMod.BalancedItems.Patches.RoundManagerPatches.ChangeScrapRarity (SelectableLevel level, SpawnableItemWithRarity spawnableScrap) (at <7c71e88d820b4b028dca708472432742>:IL_010F)
GuysNight.LethalCompanyMod.BalancedItems.Patches.RoundManagerPatches.SpawnScrapInLevelPrefix (RoundManager __instance) (at <7c71e88d820b4b028dca708472432742>:IL_00CB)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SpawnScrapInLevel>(RoundManager)
RoundManager.GeneratedFloorPostProcessing () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0009)
RoundManager+<LoadNewLevelWait>d__118.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[16:37:47.7391854] [Error  : Unity Log] KeyNotFoundException: The given key 'Candy' was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:IL_001E)
GuysNight.LethalCompanyMod.BalancedItems.Patches.RoundManagerPatches.ChangeScrapRarity (SelectableLevel level, SpawnableItemWithRarity spawnableScrap) (at <7c71e88d820b4b028dca708472432742>:IL_010F)
GuysNight.LethalCompanyMod.BalancedItems.Patches.RoundManagerPatches.SpawnScrapInLevelPrefix (RoundManager __instance) (at <7c71e88d820b4b028dca708472432742>:IL_00CB)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::SpawnScrapInLevel>(RoundManager)
RoundManager.GeneratedFloorPostProcessing () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0009)
RoundManager+<LoadNewLevelWait>d__118.MoveNext () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_013C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by Doug-Murphy** [comment]
@MathiusXII I'm sorry but mod incompatibilities are usually pretty hard to track down, and even harder to resolve most times. I did a quick look at the LethalQuantities mod and see that it is setting explicit priority values for when to run various methods inside of there. That could definitely be the issue with the incompatibility here.

Unfortunately, I just don't have the time to continue supporting these mods to that degree. I'm happy to pass the torch and accept PRs from the community for the larger effort issues though! Otherwise, I only have the time at the moment to continue with minor bug fixes. Sorry for the bad news!

**Comment by MathiusXII** [comment]
@Doug-Murphy It's not really an incompatibility I don't think. It seems like BalancedItems still runs moon rarities even when it's set to false. That should be a simple fix, right?

**Comment by Doug-Murphy** [comment]
> If I add these items with LQ, BalancedItems softlocks on random seed and prints these errors in the console.

This defines mod incompatibility.

> It seems like BalancedItems still runs moon rarities even when it's set to false. That should be a simple fix, right?

It runs moon rarities, but applies vanilla values instead of overridden values. The reasoning is so that you can toggle the feature and not have to restart your game every time.

**Comment by MathiusXII** [comment]
Well it would work fine if there was a proper way to turn off moon rarities entirely. That's all I'm saying.
If you don't want to add that, that's fine. I'll continue using BalancedItems for moon rarities instead of LethalQuantities.
